### ISSUE TITLE
Excuse me, are there any methods to handle this case?

### ISSUE THREAD

**Issue by ycq0125** [mahaloz/cfgutils#1]
[test.zip](https://github.com/mahaloz/cfgutils/files/11071112/test.zip)

Hello, I tried to perform interval analysis on the code in the compressed file above, but I encountered some performance issues, and I also noticed that there are some problems. I have submitted the issue at https://github.com/angr/angr/issues/3877.
If possible, could you provide some suggestions for me? It's important to me. Thank you.

**Comment by mahaloz** [comment]
Hi @ycq0125, this code is quite literally a direct port from angr, but to work with non-angr specific CFGs. For the Region Analysis we do, that linked issue should still be a problem here.
